---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "500m"
    limits.cpu: "100-m"
    requests.memory: "50mi
    limits.memory: "100mi"
