---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "500m"
    limits.cpu: "100m"
    requests.memory: "50Mi"
    limits.memory: "100Mi"
