---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  USERNAME: "bXVzdGFmYQo="
  PASSWORD: "SHlkCg=="


through command

kubectl create secret generic my-secret --from-literal=USERNAME=mustafa --from-literal=PASSWORD=1234
