---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: flm
spec:
  replicas: 3
  selector:
    app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
