---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont
          image: shaikmustafa/paytm:movie
          ports:
            - containerPort: 80
